export const mockProducts = [
  {
    id: 1,
    name: 'Class 9 Science (NCERT)',
    category: 'SCHOOL BOOKS',
    description: 'Full curriculum textbook. Recommended for student.',
    mrp: 480,
    studentPrice: 360,
    memberPrice: 432,
    studentDiscount: 25,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625313/zenk_market/dyct66vllhawwwa9c3vr.jpg',
    emoji: '📚'
  },
  {
    id: 2,
    name: 'Class 9 Maths (NCERT)',
    category: 'SCHOOL BOOKS',
    description: 'Covers algebra, geometry and statistics.',
    mrp: 420,
    studentPrice: 315,
    memberPrice: 378,
    studentDiscount: 25,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625314/zenk_market/dhrmf1bzuibssygzbohq.jpg',
    emoji: '📘'
  },
  {
    id: 3,
    name: 'Class 9 English (NCERT)',
    category: 'SCHOOL BOOKS',
    description: 'Beehive and Moments literature set.',
    mrp: 360,
    studentPrice: 270,
    memberPrice: 324,
    studentDiscount: 25,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625384/zenk_market/hvn4atp5cwnecmw9j39b.jpg',
    emoji: '📖'
  },
  {
    id: 4,
    name: 'Atomic Habits — James Clear',
    category: 'FICTION',
    description: 'Self-improvement. Available for members.',
    mrp: 499,
    studentPrice: null, 
    memberPrice: 449,
    studentDiscount: 0,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625385/zenk_market/diqunocbwgmmfg1y1uch.jpg',
    emoji: '📗'
  },
  {
    id: 5,
    name: 'Premium Stationery Pack',
    category: 'STATIONERY',
    description: 'Pens, pencils, eraser, ruler, geometry set.',
    mrp: 650,
    studentPrice: 520,
    memberPrice: 585,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625317/zenk_market/dqg19yxgri92zt0dswc1.jpg',
    emoji: '✏️'
  },
  {
    id: 6,
    name: 'A4 Notebook Set (5 pcs)',
    category: 'STATIONERY',
    description: '200-page ruled notebooks. Index tabbed.',
    mrp: 280,
    studentPrice: 224,
    memberPrice: 252,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625317/zenk_market/odxn1rqslqrj7levtgvu.jpg',
    emoji: '📓'
  },
  {
    id: 7,
    name: 'Scientific Calculator (Casio)',
    category: 'STATIONERY',
    description: 'Approved for CBSE Class 9 onwards.',
    mrp: 1200,
    studentPrice: 1020,
    memberPrice: 1080,
    studentDiscount: 15,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625385/zenk_market/rcwauskjldi4iqqaiaq8.jpg',
    emoji: '🔢'
  },
  {
    id: 8,
    name: 'Drawing & Art Supply Kit',
    category: 'STATIONERY',
    description: 'Pencils, colours, sketch pad. For art students.',
    mrp: 480,
    studentPrice: 384,
    memberPrice: 432,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625319/zenk_market/bqvybpsz66wlmyjtzvps.jpg',
    emoji: '🎨'
  },
  {
    id: 9,
    name: 'School Bag (15L, waterproof)',
    category: 'STATIONERY',
    description: 'Durable backpack with laptop compartment.',
    mrp: 1500,
    studentPrice: 1050,
    memberPrice: 1260,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    outOfStock: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625320/zenk_market/dghjekqws2hx2gp42lcn.jpg',
    emoji: '🎒'
  },
  {
    id: 10,
    name: 'Lenovo IdeaPad 3 Laptop (i3, 8GB)',
    category: 'ELECTRONICS',
    description: '15.6" HD, 256GB SSD. Approved for students.',
    mrp: 38000,
    studentPrice: 33440,
    memberPrice: 34960,
    studentDiscount: 12,
    memberDiscount: 8,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625386/zenk_market/bms5vfp4lg7n4wb7padl.jpg',
    emoji: '💻'
  },
  {
    id: 11,
    name: 'Samsung Tab A9 (WiFi, 4GB/64GB)',
    category: 'ELECTRONICS',
    description: '10.5" display. Perfect for digital learning.',
    mrp: 18000,
    studentPrice: 15840,
    memberPrice: 16560,
    studentDiscount: 12,
    memberDiscount: 8,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625387/zenk_market/bgdm7y4tmrzit9we0evk.jpg',
    emoji: '📱'
  },
  {
    id: 12,
    name: 'Noise-cancelling Headphones (Boat)',
    category: 'ELECTRONICS',
    description: 'For focused study. USB-C charging.',
    mrp: 2200,
    studentPrice: 1980,
    memberPrice: 2024,
    studentDiscount: 10,
    memberDiscount: 8,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625322/zenk_market/kg1il7pyfxfufbq1rlnq.jpg',
    emoji: '🎧'
  },
  {
    id: 13,
    name: 'LED Desk Lamp (USB, adjustable)',
    category: 'ELECTRONICS',
    description: 'Eye-care lamp. 5 brightness levels.',
    mrp: 999,
    studentPrice: 849,
    memberPrice: 899,
    studentDiscount: 15,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625323/zenk_market/yht7ecuxtjznzu9fdksn.jpg',
    emoji: '💡'
  },
  {
    id: 14,
    name: 'Jio 6-Month Data Plan (40GB/month)',
    category: 'CONNECTIVITY',
    description: 'SIM + recharge. For home study. ZenK arranged.',
    mrp: 1800,
    studentPrice: 1440,
    memberPrice: 1620,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625388/zenk_market/rhrss5spizfhv6s7rknj.jpg',
    emoji: '📡'
  },
  {
    id: 15,
    name: 'Home WiFi Router (TP-Link, dual-band)',
    category: 'CONNECTIVITY',
    description: 'Reliable home broadband router.',
    mrp: 2400,
    studentPrice: 2040,
    memberPrice: 2208,
    studentDiscount: 15,
    memberDiscount: 8,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625324/zenk_market/geijxiez6xmaos0pntbb.jpg',
    emoji: '🔌'
  },
  {
    id: 16,
    name: 'Mobile Holder + Ring Light Set',
    category: 'CONNECTIVITY',
    description: 'For online classes and video calls.',
    mrp: 850,
    studentPrice: 722,
    memberPrice: 765,
    studentDiscount: 15,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1703080000/zenk_market/placeholder.jpg',
    emoji: '📷'
  },
  {
    id: 17,
    name: 'Study Table & Chair Set (solid wood)',
    category: 'FURNITURE',
    description: '120cm desk with drawer. Ergonomic chair.',
    mrp: 6500,
    studentPrice: 5200,
    memberPrice: 5850,
    studentDiscount: 20,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625326/zenk_market/fhyidaqpu065qmqev2zs.jpg',
    emoji: '🪑'
  },
  {
    id: 18,
    name: 'Bookshelf (5-tier, metal frame)',
    category: 'FURNITURE',
    description: 'Sturdy 5-shelf unit. Assembly included.',
    mrp: 3200,
    studentPrice: 2720,
    memberPrice: 2880,
    studentDiscount: 15,
    memberDiscount: 10,
    approved: true,
    image: 'https://res.cloudinary.com/dhlmxyh9f/image/upload/v1776625327/zenk_market/fhrnpadn9avgim7lno23.jpg',
    emoji: '📚'
  }
];

export const mockCategories = [
  { name: 'All Items', count: 18 },
  { name: 'School books', count: 3 },
  { name: 'Fiction', count: 1 },
  { name: 'Stationery', count: 5 },
  { name: 'Electronics', count: 4 },
  { name: 'Connectivity', count: 3 },
  { name: 'Furniture', count: 2 }
];
